# Generated by Django 5.1.2 on 2025-01-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0002_dog_rasa_psa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='castrated',
            field=models.CharField(choices=[('YES', 'TAK'), ('NO', 'NIE')], default='', max_length=10),
        ),
    ]
