# Generated by Django 5.1.2 on 2025-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0004_rename_dog_size_dog_size_alter_dog_age_type_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='team',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='cat',
            name='team',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
