# Generated by Django 5.1.2 on 2025-01-24 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0006_money_collection_shelter_user_cat_image_cat_opis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cage',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shelter',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shelter',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
