# Generated by Django 5.1.2 on 2025-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0007_cage_created_cage_updated_shelter_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age_type',
            field=models.CharField(choices=[('kitten', 'Kociak'), ('puppy', 'Szczeniak'), ('age', 'Wiek'), ('adult', 'dorosly')], default='age', max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_type',
            field=models.CharField(choices=[('kitten', 'Kociak'), ('puppy', 'Szczeniak'), ('age', 'Wiek'), ('adult', 'dorosly')], default='age', max_length=10),
        ),
    ]
