# Generated by Django 5.1.2 on 2025-01-25 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0008_alter_cat_age_type_alter_dog_age_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='castrated',
            field=models.CharField(choices=[('YES', 'TAK'), ('NO', 'NIE'), ('', 'Nie podano')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='rasa_kota',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='dog',
            name='castrated',
            field=models.CharField(choices=[('YES', 'TAK'), ('NO', 'NIE'), ('', 'Nie podano')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='rasa_psa',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Wpisz poprawny adres email')]),
        ),
    ]
