# Generated by Django 5.1.2 on 2025-01-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0009_alter_cat_castrated_alter_cat_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Osoba',
        ),
    ]
