# Generated by Django 5.1.2 on 2025-01-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0010_rename_user_osoba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
